include ../common/Makefile.def

TARGET = test-cppunit-listener$(EXE)

SOURCES = \
    src/main.cpp

INCLUDE= -I../test-cppunit-basic/src -I../test-cppunit-test-log/src
LIB= -lcppunit
CXX_FLAGS += 

include ../common/Makefile.in
