include ../common/Makefile.def

TARGET = simple-http-server$(EXE)

SOURCES = \
    src/main.cpp \
    src/server.cpp \
    src/connection.cpp \
    src/connection_manager.cpp \
    src/mime_types.cpp \
    src/reply.cpp \
    src/request_handler.cpp \
    src/request_parser.cpp

INCLUDE= -I../driver/src
LIB=
CXX_FLAGS += 

include ../common/Makefile.in
